# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import history.models.character


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=history.models.character.get_image_path)),
            ],
        ),
    ]
